import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase/server";
import type { User, UserStatus, UserRole } from "@/types";
import bcrypt from "bcryptjs";
import crypto from "crypto";

// Database types
interface DbUser {
  id: string;
  name: string;
  email: string;
  password: string;
  role: "owner" | "receptionist";
  created_at: string;
  updated_at: string;
  status?: UserStatus | null;
}

function dbUserToUser(dbUser: DbUser): User {
  const numericId =
    parseInt(dbUser.id.replace(/-/g, "").substring(0, 8), 16) % 1000000;
  return {
    id: numericId,
    dbId: dbUser.id,
    name: dbUser.name,
    email: dbUser.email,
    // Do not expose password hashes to the client
    role: dbUser.role,
    status: (dbUser.status as UserStatus) || "active",
  };
}

function userToDbUser(
  user: Omit<User, "id" | "dbId">
): Omit<DbUser, "id" | "created_at" | "updated_at"> {
  return {
    name: user.name,
    email: user.email,
    // password is handled separately (hashed) before insert/update
    password: user.password ?? "",
    role: user.role,
    status: user.status ?? "active",
  };
}

async function logAuditAction(params: {
  actorId?: string;
  actorName?: string;
  actorRole?: UserRole;
  action: string;
  context?: string;
}) {
  const { actorId, actorName, actorRole, action, context } = params;
  if (!actorId || !actorName || !actorRole) return;

  const { error } = await supabase.from("audit_logs").insert({
    actor_id: actorId,
    actor_name: actorName,
    actor_role: actorRole,
    action,
    context: context ?? null,
  });

  if (error) {
    console.error("Failed to write audit log (users):", error);
  }
}

// GET /api/users - Get all users (without passwords)
export async function GET() {
  try {
    const { data, error } = await supabase.from("users").select("*");

    if (error) {
      console.error("Error fetching users:", error);
      return NextResponse.json(
        { error: `Failed to fetch users: ${error.message}` },
        { status: 500 }
      );
    }

    const users = (data || []).map(dbUserToUser);
    return NextResponse.json({ users });
  } catch (error: any) {
    console.error("Error in GET /api/users:", error);
    return NextResponse.json(
      { error: error?.message || "Internal server error" },
      { status: 500 }
    );
  }
}

// POST /api/users - Create a new user (e.g. owner or receptionist)
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const user: Omit<User, "id" | "dbId"> = body.user ?? body;
    const actor = body.actor as
      | { id: string; name: string; role: UserRole }
      | undefined;
    
    // Check if user already exists
    const { data: existingUser } = await supabase
      .from("users")
      .select("email")
      .eq("email", user.email)
      .single();
    
    if (existingUser) {
      // User already exists, return the existing user
      const { data: fullUser } = await supabase
        .from("users")
        .select("*")
        .eq("email", user.email)
        .single();
      
      if (fullUser) {
        const existingUserData = dbUserToUser(fullUser as DbUser);
        return NextResponse.json({ user: existingUserData }, { status: 200 });
      }
    }
    
    // Hash password before storing.
    // If no password is provided (e.g. owner-created receptionist),
    // generate a secure random temporary password so the account exists
    // but the user must set their real password via the "forgot password" flow.
    const plainPassword =
      user.password && user.password.trim().length > 0
        ? user.password
        : crypto.randomBytes(32).toString("hex");

    const hashedPassword = await bcrypt.hash(plainPassword, 10);
    const dbUser = {
      ...userToDbUser(user),
      password: hashedPassword,
    }; // id will be generated by DB
    const { data, error } = await supabase
      .from("users")
      .insert(dbUser)
      .select()
      .single();

    if (error) {
      // Handle duplicate key error gracefully
      if (error.code === "23505" || error.message?.includes("duplicate key") || error.message?.includes("unique constraint")) {
        // User was created between check and insert, fetch and return existing user
        const { data: fullUser } = await supabase
          .from("users")
          .select("*")
          .eq("email", user.email)
          .single();
        
        if (fullUser) {
          const existingUserData = dbUserToUser(fullUser as DbUser);
          return NextResponse.json({ user: existingUserData }, { status: 200 });
        }
      }
      
      console.error("Error creating user:", error);
      return NextResponse.json(
        { error: `Failed to create user: ${error.message}` },
        { status: 500 }
      );
    }

    const createdUser = dbUserToUser(data as DbUser);

    // Log receptionist creation if actor info is provided
    if (actor && createdUser.role === "receptionist") {
      await logAuditAction({
        actorId: actor.id,
        actorName: actor.name,
        actorRole: actor.role,
        action: "create_receptionist",
        context: createdUser.email,
      });
    }

    return NextResponse.json({ user: createdUser }, { status: 201 });
  } catch (error: any) {
    console.error("Error in POST /api/users:", error);
    return NextResponse.json(
      { error: error?.message || "Internal server error" },
      { status: 500 }
    );
  }
}
