import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase/server";
import type { User } from "@/types";

// Database types
interface DbUser {
  id: string;
  name: string;
  email: string;
  password: string;
  role: "owner" | "receptionist";
  created_at: string;
  updated_at: string;
}

function dbUserToUser(dbUser: DbUser): User {
  const numericId = parseInt(dbUser.id.replace(/-/g, "").substring(0, 8), 16) % 1000000;
  return {
    id: numericId,
    name: dbUser.name,
    email: dbUser.email,
    password: dbUser.password,
    role: dbUser.role,
  };
}

function userToDbUser(user: User): Omit<DbUser, "id" | "created_at" | "updated_at"> {
  return {
    name: user.name,
    email: user.email,
    password: user.password,
    role: user.role,
  };
}

// GET /api/users - Get all users
export async function GET() {
  try {
    const { data, error } = await supabase.from("users").select("*");

    if (error) {
      console.error("Error fetching users:", error);
      return NextResponse.json(
        { error: `Failed to fetch users: ${error.message}` },
        { status: 500 }
      );
    }

    const users = (data || []).map(dbUserToUser);
    return NextResponse.json({ users });
  } catch (error: any) {
    console.error("Error in GET /api/users:", error);
    return NextResponse.json(
      { error: error?.message || "Internal server error" },
      { status: 500 }
    );
  }
}

// POST /api/users - Create a new user
export async function POST(request: NextRequest) {
  try {
    const user: Omit<User, "id"> = await request.json();
    const dbUser = userToDbUser({ ...user, id: 0 }); // id will be generated by DB
    
    const { data, error } = await supabase.from("users").insert(dbUser).select().single();

    if (error) {
      console.error("Error creating user:", error);
      return NextResponse.json(
        { error: `Failed to create user: ${error.message}` },
        { status: 500 }
      );
    }

    const createdUser = dbUserToUser(data as DbUser);
    return NextResponse.json({ user: createdUser }, { status: 201 });
  } catch (error: any) {
    console.error("Error in POST /api/users:", error);
    return NextResponse.json(
      { error: error?.message || "Internal server error" },
      { status: 500 }
    );
  }
}
